BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Users" (
	"id"	INTEGER,
	"username"	VARCHAR(255) NOT NULL,
	"email"	VARCHAR(255) NOT NULL UNIQUE,
	"password"	VARCHAR(255) NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Genero" (
	"id"	INTEGER,
	"name"	VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Director" (
	"id"	INTEGER,
	"name"	VARCHAR(255) NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Movies" (
	"id"	INTEGER,
	"title"	VARCHAR(255) NOT NULL,
	"sinopsis"	TEXT NOT NULL,
	"image_url"	VARCHAR(255) NOT NULL,
	"id_director"	INTEGER NOT NULL,
	"id_genero"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("id_director") REFERENCES "Director"("id") ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY("id_genero") REFERENCES "Genero"("id") ON DELETE NO ACTION ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Comentarios" (
	"id"	INTEGER,
	"id_Movie"	INTEGER NOT NULL,
	"id_User"	INTEGER NOT NULL,
	"Date"	DATE,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("id_Movie") REFERENCES "Movie"("id") ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY("id_User") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE CASCADE
);
COMMIT;
